name: Transform tokens send from figma
on:
  repository_dispatch:
    # and the event_type property from the request body is 'update-tokens'
    types: update-tokens
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
          - uses: actions/checkout@v2
          # this creates a json file from the stringified json from the request body
          - name: create json from request body
            id: create-json
            uses: jsdaniell/create-json@1.1.2
            with:
              # it uses the name from your settings that was send as then tokenFileName parameter
              name: 'design-tokens-example.json'
              # it uses the json string that was send as the tokens parameter
              json: ${{ github.event.client_payload.tokens }}
          - run: ls
          - run: cat design-tokens-example.json
          - name: Setup Node.js environment
            uses: actions/setup-node@v2.4.0
          - run: npm i -g npm && npm i --save lodash
          # Convert tokens according to Style Dictionary config
          - run: npx style-dictionary build --config config.js
          # Add files that were created during a run, e.g. created files from style dictionary.
          - uses: stefanzweifel/git-auto-commit-action@v4
            with:
              commit_message: Update Tokens
